contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseurl = "http://breakit100.github.io"
languageCode = "en-us"
title = "Breakit's hugo Site"

canonifyurls = true

# Theme to use (located in /themes/THEMENAME/)
theme = "hugo-bootstrap-premium"


[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "breakit"
    email = "breakit100@gmail.com"
